---

- name: privileged
  become: true
  become_user: root
  block:
    - name: gnome-shell
      with_items: "{{ _pgs_packages }}"
      package:
        name: "{{ item }}"

    - name: arc-theme
      with_items: "{{ _pgs_arc_theme }}"
      package:
        name: "{{ item }}"

    - name: extension manager
      package:
        name: gnome-extensions-app
      when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 34
